---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nextcloud-files.yaml
- nextcloud-mariadb.yaml
- nextcloud-redis-master.yaml
- nextcloud-redis-replicas.yaml
- palworld.yaml
- growi-uploads.yaml
- growi-mongodb.yaml
- growi-elasticsearch-master.yaml
- growi-elasticsearch-data.yaml
- growi-backup-backup-dir.yaml
- growi-backup-attachments-dir.yaml
- rss-generator-mariadb-primary.yaml
- rss-generator-mariadb-secondary.yaml
- growi-converter-attachment.yaml
- minecraft-datadir.yaml
- minecraft-backupdir.yaml
- minecraft-mariadb.yaml
