---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-mariadb-pv
  labels:
    target-app: minecraft-mariadb
spec:
  capacity:
    storage: 32Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /data/k8s/pv/minecraft/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
