---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
resources:
- cronjob.yaml
- role.yaml
- rolebinding.yaml
- serviceaccount.yaml
configMapGenerator:
- name: restart-deployment-cm
  files:
  - ./config/restart-deployment.sh
