---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 69.2.1
  releaseName: kube-prometheus-stack
  namespace: monitoring
  valuesFile: values.yaml
  valuesMerge: override
  includeCRDs: true
resources:
- prometheus-pvc.yaml
- alertmanager-pvc.yaml
- grafana-pvc.yaml
