---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
helmCharts:
- name: minecraft
  repo: https://itzg.github.io/minecraft-server-charts/
  releaseName: minecraft
  namespace: minecraft
  version: 4.23.0
  valuesFile: values.yaml
  valuesMerge: override
resources:
- minecraft-datadir-pvc.yaml
- minecraft-backupdir-pvc.yaml
