---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
helmCharts:
- name: minecraft
  repo: https://itzg.github.io/minecraft-server-charts/
  releaseName: minecraft
  namespace: minecraft
  version: 4.23.0
  valuesFile: values-minecraft.yaml
  valuesMerge: override
- name: mariadb
  repo: https://charts.bitnami.com/bitnami
  version: 19.0.5
  releaseName: mariadb
  namespace: minecraft
  valuesFile: values-mariadb.yaml
  valuesMerge: override
resources:
- network-policy.yaml
- minecraft-datadir-pvc.yaml
- minecraft-backupdir-pvc.yaml
