---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minecraft-network-policy
  namespace: minecraft
spec:
  podSelector:
    matchLabels:
      app: minecraft-minecraft
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 149.28.20.40/32
    - ipBlock:
        cidr: 192.168.0.0/24
    - podSelector:
        matchLabels:
          app: minecraft-minecraft
    ports:
    - protocol: TCP
      port: 25565
    - protocol: UDP
      port: 25565
