---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rss-notifier
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- cronjob.yaml
helmCharts:
- name: mariadb
  repo: oci://registry-1.docker.io/bitnamicharts
  version: 21.0.3
  releaseName: mariadb
  namespace: rss-notifier
  valuesFile: values-mariadb.yaml
  valuesMerge: override
